import { defineStore } from 'pinia'
import { computed, ref } from 'vue'

type ThemeKey = 'light' | 'blue' | 'green' | 'purple' | 'warm' | 'gray' | 'dark'

type ThemeConfig = {
  key: ThemeKey
  name: string
  description: string
  previewColor: string
  variables: Record<string, string>
}

const THEME_STORAGE_KEY = 'system_theme_key'

const themeList: ThemeConfig[] = [
  {
    key: 'light',
    name: '明亮',
    description: '清爽通透的白色系界面，适合日间使用。',
    previewColor: '#7aa2ff',
    variables: {
      '--theme-color': '#5f86e8',
      '--theme-color-hover': '#4d72ca',
      '--theme-color-soft': '#f3f7ff',
      '--theme-color-border': '#dce6ff',
      '--app-bg': '#fbfcff',
      '--panel-bg': '#ffffff',
      '--panel-bg-soft': '#f8faff',
      '--card-bg': '#ffffff',
      '--dialog-bg': '#ffffff',
      '--reading-bg': '#fffef9',
      '--text-primary': '#1f2937',
      '--text-secondary': '#5f6b7a',
      '--text-muted': '#9aa3b2',
      '--border-color': '#e6ebf2',
      '--dialog-overlay': 'rgba(31, 41, 55, 0.32)',
      '--success-color': '#3f8f56',
      '--success-bg': '#eef8f0',
      '--success-border': '#cfe8d5',
      '--info-color': '#3478c9',
      '--info-bg': '#eef6ff',
      '--info-border': '#cfe3f8',
      '--danger-color': '#b34d43',
      '--danger-bg': '#fff5f3',
      '--danger-border': '#efd1cc',
      '--warning-color': '#95672b',
      '--warning-bg': '#fff8ec',
      '--warning-border': '#ead9bd',
      '--disabled-bg': '#f1f3f6',
      '--disabled-text': '#a6afbd',
      '--hover-bg': '#f4f7fb',
      '--shadow-soft': '0 12px 30px rgba(31, 41, 55, 0.07)',
    },
  },
  {
    key: 'blue',
    name: '静谧蓝',
    description: '清爽但降低饱和度，适合长时间写作。',
    previewColor: '#4f7cff',
    variables: {
      '--theme-color': '#5576d9',
      '--theme-color-hover': '#4764bd',
      '--theme-color-soft': '#f0f4ff',
      '--theme-color-border': '#d8e2ff',
      '--app-bg': '#f7f8fb',
      '--panel-bg': '#ffffff',
      '--panel-bg-soft': '#f9fafc',
      '--card-bg': '#ffffff',
      '--dialog-bg': '#ffffff',
      '--reading-bg': '#fffdf6',
      '--text-primary': '#202735',
      '--text-secondary': '#606b7b',
      '--text-muted': '#8d96a6',
      '--border-color': '#e7eaf1',
      '--dialog-overlay': 'rgba(32, 39, 53, 0.34)',
      '--success-color': '#438b59',
      '--success-bg': '#eef8f0',
      '--success-border': '#cfe7d4',
      '--info-color': '#3d72c4',
      '--info-bg': '#eef5ff',
      '--info-border': '#d4e2fb',
      '--danger-color': '#b34d43',
      '--danger-bg': '#fff5f3',
      '--danger-border': '#efd1cc',
      '--warning-color': '#95672b',
      '--warning-bg': '#fff8ec',
      '--warning-border': '#ead9bd',
      '--disabled-bg': '#f1f3f6',
      '--disabled-text': '#a4acba',
      '--hover-bg': '#f4f7fb',
      '--shadow-soft': '0 12px 30px rgba(32, 39, 53, 0.07)',
    },
  },
  {
    key: 'green',
    name: '森林绿',
    description: '温和自然的绿色强调，减少荧光感。',
    previewColor: '#4f8f6b',
    variables: {
      '--theme-color': '#56846a',
      '--theme-color-hover': '#456e56',
      '--theme-color-soft': '#f0f7f2',
      '--theme-color-border': '#d8e8dd',
      '--app-bg': '#f7f9f6',
      '--panel-bg': '#ffffff',
      '--panel-bg-soft': '#f9fbf8',
      '--card-bg': '#ffffff',
      '--dialog-bg': '#ffffff',
      '--reading-bg': '#fffdf4',
      '--text-primary': '#26332b',
      '--text-secondary': '#627064',
      '--text-muted': '#8e998f',
      '--border-color': '#e5ece2',
      '--dialog-overlay': 'rgba(38, 51, 43, 0.34)',
      '--success-color': '#4d8b61',
      '--success-bg': '#eff8f1',
      '--success-border': '#d2e8d7',
      '--info-color': '#3c788b',
      '--info-bg': '#eef8fb',
      '--info-border': '#d2e7ed',
      '--danger-color': '#ad4f45',
      '--danger-bg': '#fff5f3',
      '--danger-border': '#efd2cd',
      '--warning-color': '#90672e',
      '--warning-bg': '#fff8ec',
      '--warning-border': '#e9d9bf',
      '--disabled-bg': '#f0f3ef',
      '--disabled-text': '#a1aaa1',
      '--hover-bg': '#f2f7f3',
      '--shadow-soft': '0 12px 30px rgba(38, 51, 43, 0.07)',
    },
  },
  {
    key: 'purple',
    name: '雅致紫',
    description: '柔和创作氛围，适合剧情编辑场景。',
    previewColor: '#7c6ee6',
    variables: {
      '--theme-color': '#7a70cf',
      '--theme-color-hover': '#675cba',
      '--theme-color-soft': '#f4f2ff',
      '--theme-color-border': '#ddd9fb',
      '--app-bg': '#f8f7fb',
      '--panel-bg': '#ffffff',
      '--panel-bg-soft': '#faf9fd',
      '--card-bg': '#ffffff',
      '--dialog-bg': '#ffffff',
      '--reading-bg': '#fffdf7',
      '--text-primary': '#29283a',
      '--text-secondary': '#69667a',
      '--text-muted': '#9390a0',
      '--border-color': '#e9e6f0',
      '--dialog-overlay': 'rgba(41, 40, 58, 0.34)',
      '--success-color': '#4f875e',
      '--success-bg': '#eff8f1',
      '--success-border': '#d3e8d8',
      '--info-color': '#665fc2',
      '--info-bg': '#f2f1ff',
      '--info-border': '#dcd9f8',
      '--danger-color': '#b04d46',
      '--danger-bg': '#fff5f4',
      '--danger-border': '#efd1ce',
      '--warning-color': '#95662d',
      '--warning-bg': '#fff8ec',
      '--warning-border': '#ead8bd',
      '--disabled-bg': '#f2f1f6',
      '--disabled-text': '#aaa6b4',
      '--hover-bg': '#f5f3fa',
      '--shadow-soft': '0 12px 30px rgba(41, 40, 58, 0.07)',
    },
  },
  {
    key: 'warm',
    name: '暖橙',
    description: '偏暖的低刺激配色，阅读区域更柔和。',
    previewColor: '#c9823f',
    variables: {
      '--theme-color': '#bd7b3f',
      '--theme-color-hover': '#9f6735',
      '--theme-color-soft': '#fff5e9',
      '--theme-color-border': '#ecd4b8',
      '--app-bg': '#faf7f1',
      '--panel-bg': '#ffffff',
      '--panel-bg-soft': '#fdfaf5',
      '--card-bg': '#ffffff',
      '--dialog-bg': '#ffffff',
      '--reading-bg': '#fff8eb',
      '--text-primary': '#352d25',
      '--text-secondary': '#75695e',
      '--text-muted': '#9b9289',
      '--border-color': '#eee3d6',
      '--dialog-overlay': 'rgba(53, 45, 37, 0.34)',
      '--success-color': '#5f8750',
      '--success-bg': '#f2f8ed',
      '--success-border': '#d9e8ce',
      '--info-color': '#a06b35',
      '--info-bg': '#fff5e8',
      '--info-border': '#ead3b4',
      '--danger-color': '#ad4d42',
      '--danger-bg': '#fff5f2',
      '--danger-border': '#efd0ca',
      '--warning-color': '#8d622c',
      '--warning-bg': '#fff7e8',
      '--warning-border': '#e8d5b7',
      '--disabled-bg': '#f3eee6',
      '--disabled-text': '#aaa095',
      '--hover-bg': '#f8f1e7',
      '--shadow-soft': '0 12px 30px rgba(53, 45, 37, 0.07)',
    },
  },
  {
    key: 'gray',
    name: '石墨灰',
    description: '低饱和强调色，适合减少视觉刺激。',
    previewColor: '#5f6b7a',
    variables: {
      '--theme-color': '#64707f',
      '--theme-color-hover': '#535e6b',
      '--theme-color-soft': '#f3f5f7',
      '--theme-color-border': '#dbe1e8',
      '--app-bg': '#f6f7f8',
      '--panel-bg': '#ffffff',
      '--panel-bg-soft': '#f9fafb',
      '--card-bg': '#ffffff',
      '--dialog-bg': '#ffffff',
      '--reading-bg': '#fffdf6',
      '--text-primary': '#252b34',
      '--text-secondary': '#636c77',
      '--text-muted': '#9199a3',
      '--border-color': '#e3e7ec',
      '--dialog-overlay': 'rgba(37, 43, 52, 0.34)',
      '--success-color': '#527e5e',
      '--success-bg': '#f0f6f1',
      '--success-border': '#d4e5d7',
      '--info-color': '#5b6f8a',
      '--info-bg': '#f1f5f9',
      '--info-border': '#d9e2ea',
      '--danger-color': '#ad5048',
      '--danger-bg': '#fff5f4',
      '--danger-border': '#efd2ce',
      '--warning-color': '#8f662d',
      '--warning-bg': '#fff8ec',
      '--warning-border': '#e9d8bd',
      '--disabled-bg': '#eef1f4',
      '--disabled-text': '#9fa8b2',
      '--hover-bg': '#f1f4f7',
      '--shadow-soft': '0 12px 30px rgba(37, 43, 52, 0.07)',
    },
  },
  {
    key: 'dark',
    name: '黑暗',
    description: '低亮度深色界面，适合夜间写作。',
    previewColor: '#8da2ff',
    variables: {
      '--theme-color': '#8da2ff',
      '--theme-color-hover': '#a5b5ff',
      '--theme-color-soft': '#1f2742',
      '--theme-color-border': '#3a4770',
      '--app-bg': '#10141c',
      '--panel-bg': '#171c26',
      '--panel-bg-soft': '#1d2430',
      '--card-bg': '#1a202c',
      '--dialog-bg': '#1c2330',
      '--reading-bg': '#161b24',
      '--text-primary': '#eef2f8',
      '--text-secondary': '#b9c2d0',
      '--text-muted': '#8792a4',
      '--border-color': '#2d3748',
      '--dialog-overlay': 'rgba(2, 6, 14, 0.68)',
      '--success-color': '#8bd69c',
      '--success-bg': '#173321',
      '--success-border': '#2f6340',
      '--info-color': '#93c5fd',
      '--info-bg': '#172b45',
      '--info-border': '#31557d',
      '--danger-color': '#f3a29b',
      '--danger-bg': '#3a1d1c',
      '--danger-border': '#6f3430',
      '--warning-color': '#f2ca85',
      '--warning-bg': '#332817',
      '--warning-border': '#695229',
      '--disabled-bg': '#252b36',
      '--disabled-text': '#687386',
      '--hover-bg': '#232b3a',
      '--shadow-soft': '0 14px 34px rgba(0, 0, 0, 0.38)',
    },
  },
]

export const useThemeStore = defineStore('theme', () => {
  const currentThemeKey = ref<ThemeKey>('blue')
  const themes = themeList

  const currentTheme = computed(() => themes.find((theme) => theme.key === currentThemeKey.value) || themes[0])

  const applyTheme = (themeKey: ThemeKey) => {
    const theme = themes.find((item) => item.key === themeKey) || themes[0]
    currentThemeKey.value = theme.key

    for (const [variableName, value] of Object.entries(theme.variables)) {
      document.documentElement.style.setProperty(variableName, value)
    }

    localStorage.setItem(THEME_STORAGE_KEY, theme.key)
  }

  const initTheme = () => {
    const savedThemeKey = localStorage.getItem(THEME_STORAGE_KEY) as ThemeKey | null
    const themeKey = themes.some((theme) => theme.key === savedThemeKey) ? savedThemeKey as ThemeKey : 'blue'
    applyTheme(themeKey)
  }

  return {
    currentThemeKey,
    currentTheme,
    themes,
    applyTheme,
    initTheme,
  }
})
